version: '3.8'

services:
  excalidraw:
    image: etdofresh/excalidraw-server:latest
    container_name: excalidraw-server
    ports:
      - "3000:3000"
    volumes:
      - ./saves:/app/saves
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ENABLE_FRONTEND_LOGGING=true  # Set to false to disable frontend log collection
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"